version: "3"
services:
  pg:
    image: postgres:latest
    restart: always
    container_name: pg
    environment:
      POSTGRES_USER: XML
      POSTGRES_PASSWORD: ftn
      POSTGRES_DB: XML_TEST
    ports:
      - "4003:5432"
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U XML -d "XML_TEST"']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "4100:6379"

  e-wallet:
    build: .
    container_name: e-wallet
    restart: always
    environment:
      - HOST=e-wallet
      - PORT=8082
      - DB_PG_USER=XML
      - DB_PG_HOST=pg
      - DB_PG_PASSWORD=ftn
      - DB_PG_NAME=XML_TEST
      - DB_PG_PORT=5432
      - DB_REDIS_HOST=redis
      - DB_REDIS_PORT=6379
    ports:
      - "8082:8082"
    depends_on:
      pg:
        condition: service_healthy
